spring.application.name=helpdesk-api

spring.datasource.url=jdbc:postgresql://localhost:5433/helpdesk
spring.datasource.username=helpdesk
spring.datasource.password=helpdesk
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.url=jdbc:postgresql://localhost:5433/helpdesk
spring.flyway.user=helpdesk
spring.flyway.password=helpdesk
spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

server.port=8080
